#!/usr/bin/env bash
# tests/cleanup-regression-data.sh — wipe ALL data generated by the regression
# (tests/regression.sh) from the Diernus Portal D1 + R2.
#
# What this cleans:
#   - Projects with name LIKE 'REG-TEST%' (cascades to cards, columns,
#     time_entries, comments, card_history, notifications)
#   - Files belonging to those projects (R2 objects + D1 records)
#   - Users with email LIKE 'regression-%@diernus.test' or
#     'throwaway-%@diernus.test' (cascades to invitations, password_resets,
#     email_changes, notifications)
#   - cron_log rows whose entity_id matches deleted cards/projects
#
# Targets the REMOTE database by default. Pass --local for the local dev DB.
# Use --env=staging to target the staging D1 (otherwise targets prod).
#
# Idempotent: re-runs cleanly. If there's nothing to clean, every step is a
# no-op (deletes 0 rows).
#
# Exit codes:
#   0 — all clean (or nothing to clean)
#   1 — D1 query errored

set -euo pipefail

DB_NAME="diernus-portal-db"
ENV="prod"
REMOTE_FLAG="--remote"
while [ $# -gt 0 ]; do
  case "$1" in
    --local)         REMOTE_FLAG=""; shift ;;
    --remote)        shift ;;
    --env=staging)   DB_NAME="diernus-portal-db-staging"; ENV="staging"; shift ;;
    --env=prod)      DB_NAME="diernus-portal-db"; ENV="prod"; shift ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

cd "$(dirname "$0")/../worker"
export PATH="/opt/homebrew/bin:$PATH"

R2_BUCKET="diernus-portal-files"

echo "=== Wiping regression leftovers on $ENV (${DB_NAME}) ==="

# ---------- 1. Find test data ----------
echo
echo "--- Surveying ---"
d1() { npx wrangler d1 execute "$DB_NAME" $REMOTE_FLAG --command "$1" 2>&1; }

SURVEY_USERS=$(d1 "SELECT COUNT(*) AS n FROM users WHERE email LIKE 'regression-%@diernus.test' OR email LIKE 'throwaway-%@diernus.test';")
SURVEY_PROJECTS=$(d1 "SELECT COUNT(*) AS n FROM projects WHERE name LIKE 'REG-TEST%';")
SURVEY_FILES=$(d1 "SELECT COUNT(*) AS n FROM files WHERE project_id IN (SELECT id FROM projects WHERE name LIKE 'REG-TEST%');")
echo "  test users:    $(echo "$SURVEY_USERS"    | python3 -c "import sys,re,json; d=sys.stdin.read(); m=re.search(r'\"n\":\s*(\d+)', d); print(m.group(1) if m else '?')")"
echo "  test projects: $(echo "$SURVEY_PROJECTS" | python3 -c "import sys,re,json; d=sys.stdin.read(); m=re.search(r'\"n\":\s*(\d+)', d); print(m.group(1) if m else '?')")"
echo "  test files:    $(echo "$SURVEY_FILES"    | python3 -c "import sys,re,json; d=sys.stdin.read(); m=re.search(r'\"n\":\s*(\d+)', d); print(m.group(1) if m else '?')")"

# Quick exit if nothing to do
if [ "$(echo "$SURVEY_USERS" | python3 -c "import sys,re; m=re.search(r'\"n\":\s*(\d+)', sys.stdin.read()); print(m.group(1) if m else '0')")" = "0" ] \
   && [ "$(echo "$SURVEY_PROJECTS" | python3 -c "import sys,re; m=re.search(r'\"n\":\s*(\d+)', sys.stdin.read()); print(m.group(1) if m else '0')")" = "0" ]; then
  echo
  echo "  ✓ Nothing to clean on $ENV"
  exit 0
fi

echo
echo "--- Proceeding with deletion (Ctrl-C to abort in 3s) ---"
sleep 3

# ---------- 2. Delete R2 files for REG-TEST projects ----------
# Get the r2_keys for files in REG-TEST projects, then delete from R2.
# The D1 records cascade-delete with the project, but R2 objects need
# explicit deletion (R2 has no FK awareness).
echo
echo "--- Deleting R2 file objects ---"
R2_KEYS=$(d1 "SELECT r2_key FROM files WHERE project_id IN (SELECT id FROM projects WHERE name LIKE 'REG-TEST%');" \
  | python3 -c "
import sys, json, re
raw = sys.stdin.read()
# Find the JSON block (after the wrangler header)
m = re.search(r'\[.*\]', raw, re.S)
if not m:
    sys.exit(0)
try:
    data = json.loads(m.group(0))
    for row in data[0].get('results', []):
        print(row['r2_key'])
except Exception:
    pass
")
N_DELETED=0
N_FAILED=0
if [ -z "$R2_KEYS" ]; then
  echo "  (no R2 objects to delete)"
else
  while IFS= read -r KEY; do
    [ -z "$KEY" ] && continue
    if npx wrangler r2 object delete "$R2_BUCKET" "$KEY" --remote >/dev/null 2>&1; then
      N_DELETED=$((N_DELETED+1))
    else
      N_FAILED=$((N_FAILED+1))
      echo "  ✗ failed to delete r2://$R2_BUCKET/$KEY"
    fi
  done <<< "$R2_KEYS"
  echo "  ✓ $N_DELETED R2 object(s) deleted (${N_FAILED} failed)"
fi

# ---------- 3. Delete REG-TEST projects from D1 ----------
# Cascades: columns, cards, time_entries, comments, card_history,
# files (D1 records), notifications (where project_id is set).
# files.uploaded_by is RESTRICT — but we already deleted files in step 2,
# so the only files remaining have uploaded_by pointing to test users
# (about to be deleted). To be safe, also clear uploaded_by on remaining
# files (shouldn't exist after R2 delete, but defensive).
echo
echo "--- Deleting REG-TEST projects (cascades to cards/columns/etc.) ---"
d1 "DELETE FROM projects WHERE name LIKE 'REG-TEST%';" \
  | grep -E "rows_written|success" | head -1 | sed 's/^/  /' || echo "  (deleted)"

# ---------- 4. Delete test users from D1 ----------
# Cascades: invitations (by email), password_resets, email_changes,
# notifications (where user_id is set), comments (where user_id is set).
# Note: cards.created_by is RESTRICT, but we already deleted the projects
# in step 3, so those cards are gone.
echo
echo "--- Deleting regression-* and throwaway-* users ---"
d1 "DELETE FROM users WHERE email LIKE 'regression-%@diernus.test' OR email LIKE 'throwaway-%@diernus.test';" \
  | grep -E "rows_written|success" | head -1 | sed 's/^/  /' || echo "  (deleted)"

# ---------- 5. Clean cron_log ----------
# cron_log rows reference card/project IDs that are now gone. They're
# harmless (no FK constraint) but stale. Clear them.
echo
echo "--- Cleaning stale cron_log rows ---"
d1 "DELETE FROM cron_log WHERE entity_type = 'card' AND entity_id NOT IN (SELECT id FROM cards);" \
  | grep -E "rows_written|success" | head -1 | sed 's/^/  cards: /' || echo "  (cleaned)"
d1 "DELETE FROM cron_log WHERE entity_type = 'project' AND entity_id NOT IN (SELECT id FROM projects);" \
  | grep -E "rows_written|success" | head -1 | sed 's/^/  projects: /' || echo "  (cleaned)"

# ---------- 6. Verify ----------
echo
echo "--- Post-cleanup verification ---"
POST_USERS=$(d1 "SELECT COUNT(*) AS n FROM users WHERE email LIKE 'regression-%@diernus.test' OR email LIKE 'throwaway-%@diernus.test';")
POST_PROJECTS=$(d1 "SELECT COUNT(*) AS n FROM projects WHERE name LIKE 'REG-TEST%';")
POST_FILES=$(d1 "SELECT COUNT(*) AS n FROM files WHERE project_id IN (SELECT id FROM projects WHERE name LIKE 'REG-TEST%');")
echo "  test users:    $(echo "$POST_USERS"    | python3 -c "import sys,re; m=re.search(r'\"n\":\s*(\d+)', sys.stdin.read()); print(m.group(1) if m else '?')")"
echo "  test projects: $(echo "$POST_PROJECTS" | python3 -c "import sys,re; m=re.search(r'\"n\":\s*(\d+)', sys.stdin.read()); print(m.group(1) if m else '?')")"
echo "  test files:    $(echo "$POST_FILES"    | python3 -c "import sys,re; m=re.search(r'\"n\":\s*(\d+)', sys.stdin.read()); print(m.group(1) if m else '?')")"

echo
echo "✓ $ENV regression data cleaned."
